global:
  namespace: the-economist-namespace
  appName: the-economist
  appPort: 3000
  Liveness:
    Path: /alive
    Port: 3000

image:
  repository: ed00m/the-economist
  tag: v0.3.1

deployment:
  apiVersion: apps/v1
  replicaCount: 1

namespace:
  apiVersion: v1

service:
  apiVersion: v1
  type: NodePort
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  apiVersion: extensions/v1beta1
