apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: the-economist
  namespace: the-economist-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: the-economist
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 60
      type: Resource
