apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: api-python-helloworld
  namespace: super-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-python-helloworld
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 60
      type: Resource
