apiVersion: v1
kind: Service
metadata:
  name: api-python-helloworld-clusterip
  namespace: super-api
spec:
  selector:
    app: api-python-helloworld
  type: ClusterIP
  ports:
  - name: api-python-helloworld-80
    port: 80
    targetPort: 8000
