apiVersion: v1
kind: Service
metadata:
  name: api-python-helloworld-loadbalancer-external
  namespace: super-api
spec:
  selector:
    app: api-python-helloworld
  type: LoadBalancer
  ports:
  - name: api-python-helloworld-80
    port: 80
    targetPort: 8000
