apiVersion: v1
kind: Service
metadata:
  name: api-python-helloworld-loadbalancer-internal
  namespace: super-api
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: api-python-helloworld
  type: LoadBalancer
  ports:
  - name: api-python-helloworld-80
    port: 80
    targetPort: 8000
