apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.global.appName }}
  type: {{ .Values.service.type }}
  ports:
  - name: "{{ .Values.global.appName }}-{{ .Values.global.appPort }}"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
